B1910014_NguyenThiThanhTruc/B1910014_NguyenThiThanhTruc/CHTC_1 - Copy (2)/Controllers/DonHangController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using CHTC_1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;

namespace CHTC_1.Controllers
{
    [Authorize]
    public class DonHangController : Controller
    {
        private readonly Chtc8Context _context;
        private readonly INotyfService _notyf;
        public DonHangController(Chtc8Context context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }
        public IActionResult Index(int page = 1)
        {
            var pageNumber = page;
            var pageSize = 4;
            var taikhoanID = HttpContext.Session.GetString("CustomerId");
            if (taikhoanID != null)
            {
                var khachhang = _context.NguoiDungs.AsNoTracking().SingleOrDefault(x => x.NdId == Convert.ToInt32(taikhoanID));
                if (khachhang != null)
                {
                    var lsdonhang = _context.HoaDons
                        .Include(x => x.ChiTietHoaDons).Include(t => t.Tthd).Include(p =>p.Pttt)
                        .AsNoTracking()
                        .Where(x => x.NdId == khachhang.NdId)
                        .OrderByDescending(x => x.HdNgay)
                        .ToList();
                    //ViewBag.Donhang = lsdonhang;
                    PagedList<HoaDon> models = new PagedList<HoaDon>(lsdonhang.AsQueryable(), pageNumber, pageSize);
                    return View(models);
                }

            }
            return RedirectToAction("Accounts/Login");
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.HoaDons == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons
                .Include(h => h.Nd)
                .Include(h => h.Pttt)
                .Include(h => h.Tthd)
                .FirstOrDefaultAsync(m => m.HdId == id);
            if (hoaDon == null)
            {
                return NotFound();
            }
            var chitiethoadon = _context.ChiTietHoaDons
                .Include(s => s.Sp)
                .AsNoTracking()
                .Where(x => x.HdId == hoaDon.HdId)
                .OrderBy(x => x.SpId)
                .ToList();
            ViewBag.ChiTiet = chitiethoadon;
            return View(hoaDon);
        }

    }
}

B1910014_NguyenThiThanhTruc/B1910014_NguyenThiThanhTruc/CHTC_1 - Copy (2)/Views/DonHang/Details.cshtml
@model CHTC_1.Models.HoaDon
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<ChiTietHoaDon> chitiethoadon = ViewBag.ChiTiet;
}


<section class="h-100 h-custom">
    <div class="container h-100 py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">

                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Chi tiết đơn hàng</h1>
                </div>


                <div>
                    <dl class="row">
                        <dt class="col-sm-2">
                            Tổng tiền:
                        </dt>
                        <dd class="col-sm-10">
                            @Model.HdTongtien.ToString("#,##0") VNĐ
                        </dd>
                        <dt class="col-sm-2">
                            Ngày đặt:
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.HdNgay)
                        </dd>
                        <dt class="col-sm-2">
                            Người đặt:
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Nd.NdHoten)
                        </dd>
                        <dt class="col-sm-2">
                            Phương thức thanh toán:
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Pttt.PtttTen)
                        </dd>
                        <dt class="col-sm-2">
                            Trạng thái đơn hàng:
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Tthd.TthdTrangthai)
                        </dd>
                    </dl>
                </div>


                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Sản phẩm</th>
                                <th scope="col"></th>
                                <th scope="col">Giá</th>
                                <th scope="col">Số lượng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var item in chitiethoadon)
                            {
                                <tr>
                                    <th scope="row">
                                        <div class=" align-items-center">
                                            <img src="/images/@item.Sp.SpHinhanh" class="img-fluid rounded-3"
                                                 style="width: 120px;" alt="Book">
                                        </div>
                                    </th>
                                    <td class="align-middle">
                                        <p class="mb-0" style="font-weight: 500;">@item.Sp.SpTensp</p>
                                    </td>
                                    <td class="align-middle">
                                        <p class="mb-0" style="font-weight: 500;">@item.Sp.SpGia.ToString("#,##0") VNĐ</p>
                                    </td>

                                    <td class="align-middle">
                                        <p class="mb-0" style="font-weight: 500;">@item.CthdSoluong</p>
                                    </td>
                                </tr>
                            }
                            
                        </tbody>
                    </table>
                </div>

                <div>
                    <a asp-action="Index" class="btn btn-light btn-icon-split">
                        <span class="icon text-gray-600">
                            <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">Trở lại</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

B1910014_NguyenThiThanhTruc/B1910014_NguyenThiThanhTruc/CHTC_1 - Copy (2)/Views/DonHang/Index.cshtml
@*@model IEnumerable<CHTC_1.Models.HoaDon>*@
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<CHTC_1.Models.HoaDon>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*@if(Model != null && Model.Count()>0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                   Tổng tiền
                </th>
                <th>
                    Ngày đặt
                </th>
                <th>
                    Người đặt
                </th>
                <th>
                    Phương thức thanh toán
                </th>
                <th>
                    Trạng thái
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HdTongtien)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HdNgay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nd.NdId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pttt.PtttId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tthd.TthdId)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.HdId">Xem chi tiết</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Chưa có đơn hàng nào!</p>
}
*@
<section class="h-100 h-custom">
    <div class="container h-100 py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">

                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Đơn hàng của tôi</h1>
                </div>
                @if(Model != null && Model.Count() > 0)
                {
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Tổng tiền</th>
                                    <th scope="col">Ngày đặt</th>
                                    <th scope="col">Trạng thái</th>
                                    <th scope="col">Phương thức thanh toán</th>
                                    <th scope="col">#</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var item in Model)
                                {
                                    <tr>
                                        <td class="align-middle">
                                            <p class="mb-0" style="font-weight: 500;">@item.HdTongtien.ToString("#,##0") VNĐ</p>
                                        </td>
                                        <td class="align-middle">
                                            <p class="mb-0" style="font-weight: 500;">@Html.DisplayFor(modelItem => item.HdNgay)</p>
                                        </td>

                                        <td class="align-middle">
                                            <p class="mb-0" style="font-weight: 500;">@item.Tthd.TthdTrangthai</p>
                                        </td>
                                        <td class="align-middle">
                                            <p class="mb-0" style="font-weight: 500;">@item.Pttt.PtttTen</p>
                                        </td>
                                        <td class="align-middle">
                                            @*<button asp-action="Details" asp-controller="DonHang" asp-route-id="@item.HdId" style="border:1px solid rgb(9, 122, 60);border-radius: 8px;width: 80px;color:#ccc;background-color: rgb(9, 122, 60);">Xem</button>*@
                                            <a asp-action="Details" asp-route-id="@item.HdId" class="btn btn-info">
                                                Xem
                                            </a>
                                        </td>

                                    </tr>
                                }
                                

                            </tbody>
                        </table>
                    </div>
                    <div div="row">
                        <div aria-label="Page navigation example">
                            <ul class="pagination">
                                <pager class="pager-container" list="@Model" asp-controller="DonHang" asp-action="Index" />
                            </ul>
                        </div>
                    </div>
                    <div>
                        <a asp-action="Index" asp-controller="Shop" class="btn btn-light btn-icon-split">
                            <span class="icon text-gray-600">
                                <i class="fas fa-arrow-right"></i>
                            </span>
                            <span class="text">Tiếp tục mua hàng</span>
                        </a>
                    </div>
                }
                else
                {
                    <p>Chưa có đơn hàng nào.<a asp-action="Index" asp-controller="Shop" >Mua hàng ngay!</a></p>
                }

            </div>
        </div>
    </div>
</section>